package com.flipperdevices.ifrmvp.backend.route.brands.presentation

import com.flipperdevices.ifrmvp.backend.core.route.RouteRegistry
import com.flipperdevices.ifrmvp.backend.model.BrandModel
import com.flipperdevices.ifrmvp.backend.model.BrandsResponse
import io.github.smiley4.ktorswaggerui.dsl.routing.get
import io.ktor.server.response.respond
import io.ktor.server.routing.Routing
import io.ktor.server.routing.get

internal class BrandsRouteRegistry : RouteRegistry {

    private fun Routing.statusRoute() {
        get(
            path = "manufacturers",
            builder = { with(BrandsSwagger) { createSwaggerDefinition() } },
            body = {
                var i = 0L
                val brandsResponse = BrandsResponse(
                    brands = listOf(
                        BrandModel(i++, "123TV"),
                        BrandModel(i++, "1TV"),
                        BrandModel(i++, "77"),
                        BrandModel(i++, "LG"),
                        BrandModel(i++, "Abex"),
                        BrandModel(i++, "Acer"),
                        BrandModel(i++, "ACL"),
                        BrandModel(i++, "Across"),
                        BrandModel(i++, "Acme"),
                        BrandModel(i++, "Adc"),
                        BrandModel(i++, "Advert"),
                        BrandModel(i++, "Acer Inc."),
                        BrandModel(i++, "Admiral"),
                        BrandModel(i++, "AGA AB"),
                        BrandModel(i++, "Aiwa"),
                        BrandModel(i++, "Akai"),
                        BrandModel(i++, "Alba"),
                        BrandModel(i++, "Amstrad"),
                        BrandModel(i++, "Andrea Electronics"),
                        BrandModel(i++, "Apex Digital"),
                        BrandModel(i++, "Apple Inc."),
                        BrandModel(i++, "Arcam"),
                        BrandModel(i++, "Arise India"),
                        BrandModel(i++, "Audiovox"),
                        BrandModel(i++, "AWA"),
                        BrandModel(i++, "Baird"),
                        BrandModel(i++, "Bang & Olufsen"),
                        BrandModel(i++, "Beko"),
                        BrandModel(i++, "BenQ"),
                        BrandModel(i++, "Binatone"),
                        BrandModel(i++, "Blaupunkt"),
                        BrandModel(i++, "BPL Group"),
                        BrandModel(i++, "Brionvega"),
                        BrandModel(i++, "Bush"),
                        BrandModel(i++, "Canadian General Electric (CGE)"),
                        BrandModel(i++, "Changhong"),
                        BrandModel(i++, "ChiMei"),
                        BrandModel(i++, "Compal Electronics[1]"),
                        BrandModel(i++, "Conar Instruments"),
                        BrandModel(i++, "Continental Edison"),
                        BrandModel(i++, "Cossor"),
                        BrandModel(i++, "Craig"),
                        BrandModel(i++, "Curtis Mathes Corporation"),
                        BrandModel(i++, "Daewoo"),
                        BrandModel(i++, "Dell"),
                        BrandModel(i++, "Delmonico International Corporation"),
                        BrandModel(i++, "DuMont Laboratories"),
                        BrandModel(i++, "Durabrand"),
                        BrandModel(i++, "Dynatron"),
                        BrandModel(i++, "EKCO"),
                        BrandModel(i++, "Electrohome"),
                        BrandModel(i++, "Element Electronics"),
                        BrandModel(i++, "Emerson Radio & Phonograph"),
                        BrandModel(i++, "EMI"),
                        BrandModel(i++, "English Electric"),
                        BrandModel(i++, "English Electric Valve Company"),
                        BrandModel(i++, "Farnsworth"),
                        BrandModel(i++, "Ferguson Electronics"),
                        BrandModel(i++, "Ferranti"),
                        BrandModel(i++, "Finlux (Vestel)"),
                        BrandModel(i++, "Fisher Electronics"),
                        BrandModel(i++, "Fujitsu"),
                        BrandModel(i++, "Funai"),
                        BrandModel(i++, "Geloso"),
                        BrandModel(i++, "General Electric"),
                        BrandModel(i++, "General Electric Company"),
                        BrandModel(i++, "GoldStar"),
                        BrandModel(i++, "Goodmans Industries"),
                        BrandModel(i++, "Google"),
                        BrandModel(i++, "Gradiente"),
                        BrandModel(i++, "Grundig"),
                        BrandModel(i++, "Haier"),
                        BrandModel(i++, "Hallicrafters"),
                        BrandModel(i++, "Hannspree"),
                        BrandModel(i++, "Heath Company/Heathkit"),
                        BrandModel(i++, "Hinari Domestic Appliances"),
                        BrandModel(i++, "Hisense"),
                        BrandModel(i++, "Hitachi"),
                        BrandModel(i++, "HMV"),
                        BrandModel(i++, "Hoffman Television (Cortron Ind)"),
                        BrandModel(i++, "Itel"),
                        BrandModel(i++, "ITT Corporation"),
                        BrandModel(i++, "Jensen Loudspeakers"),
                        BrandModel(i++, "JVC"),
                        BrandModel(i++, "Kenmore"),
                        BrandModel(i++, "Kent Television"),
                        BrandModel(i++, "Kloss Video"),
                        BrandModel(i++, "Kogan"),
                        BrandModel(i++, "Kolster-Brandes"),
                        BrandModel(i++, "Konka"),
                        BrandModel(i++, "Lanix"),
                        BrandModel(i++, "Le.com"),
                        BrandModel(i++, "LG Electronics (founded as GoldStar, name changed 1995)"),
                        BrandModel(i++, "Loewe"),
                        BrandModel(i++, "Luxor"),
                        BrandModel(i++, "Magnavox"),
                        BrandModel(i++, "Marantz"),
                        BrandModel(i++, "Marconiphone"),
                        BrandModel(i++, "Matsui"),
                        BrandModel(i++, "Memorex"),
                        BrandModel(i++, "Metz"),
                        BrandModel(i++, "Micromax"),
                        BrandModel(i++, "Mitsubishi"),
                        BrandModel(i++, "Mivar"),
                        BrandModel(i++, "Motorola"),
                        BrandModel(i++, "Muntz (Howard Radio)"),
                        BrandModel(i++, "Murphy Radio"),
                        BrandModel(i++, "NEC"),
                        BrandModel(i++, "Nokia"),
                        BrandModel(i++, "Nordmende"),
                        BrandModel(i++, "Onida"),
                        BrandModel(i++, "Orion (Hungary)"),
                        BrandModel(i++, "Orion (Japan)"),
                        BrandModel(i++, "Packard Bell, Teledyne Packard Bell"),
                        BrandModel(i++, "Panasonic (National)"),
                        BrandModel(i++, "Pensonic"),
                        BrandModel(i++, "Philco (Philco-Ford)"),
                        BrandModel(i++, "Philips"),
                        BrandModel(i++, "Pioneer"),
                        BrandModel(i++, "Planar Systems"),
                        BrandModel(i++, "Polaroid"),
                        BrandModel(i++, "ProLine"),
                        BrandModel(i++, "ProScan"),
                        BrandModel(i++, "Pye"),
                        BrandModel(i++, "Pyle USA"),
                        BrandModel(i++, "Quasar"),
                        BrandModel(i++, "RadioShack"),
                        BrandModel(i++, "Rauland-Borg"),
                        BrandModel(i++, "RCA"),
                        BrandModel(i++, "Realistic"),
                        BrandModel(i++, "Rediffusion"),
                        BrandModel(i++, "SABA"),
                        BrandModel(i++, "Salora"),
                        BrandModel(i++, "Salora International"),
                        BrandModel(i++, "Samsung"),
                        BrandModel(i++, "Sansui"),
                        BrandModel(i++, "Sanyo"),
                        BrandModel(i++, "Schneider Electric"),
                        BrandModel(i++, "Seiki Digital"),
                        BrandModel(i++, "Sèleco"),
                        BrandModel(i++, "Setchell Carlson"),
                        BrandModel(i++, "Sharp"),
                        BrandModel(i++, "Siemens"),
                        BrandModel(i++, "Skyworth"),
                        BrandModel(i++, "Sony"),
                        BrandModel(i++, "Soyo"),
                        BrandModel(i++, "Stromberg-Carlson"),
                        BrandModel(i++, "Supersonic"),
                        BrandModel(i++, "Sylvania"),
                        BrandModel(i++, "Symphonic"),
                        BrandModel(i++, "Tandy"),
                        BrandModel(i++, "Tatung Company"),
                        BrandModel(i++, "TCL Corporation"),
                        BrandModel(i++, "Technics"),
                        BrandModel(i++, "TECO"),
                        BrandModel(i++, "Teleavia"),
                        BrandModel(i++, "Telefunken"),
                        BrandModel(i++, "Teletronics"),
                        BrandModel(i++, "Thomson SA"),
                        BrandModel(i++, "Thorn Electrical Industries"),
                        BrandModel(i++, "Thorn EMI"),
                        BrandModel(i++, "Toshiba"),
                        BrandModel(i++, "TP Vision"),
                        BrandModel(i++, "TPV Technology"),
                        BrandModel(i++, "Ultra"),
                        BrandModel(i++, "United States Television Manufacturing Corp."),
                        BrandModel(i++, "Vestel"),
                        BrandModel(i++, "Videocon"),
                        BrandModel(i++, "Videoton"),
                        BrandModel(i++, "Vizio"),
                        BrandModel(i++, "Vu Televisions"),
                        BrandModel(i++, "Walton"),
                        BrandModel(i++, "Westinghouse Electric Corporation"),
                        BrandModel(i++, "Westinghouse Electronics"),
                        BrandModel(i++, "White-Westinghouse"),
                        BrandModel(i++, "Xiaomi"),
                        BrandModel(i++, "Zanussi"),
                        BrandModel(i++, "Zenith Radio"),
                        BrandModel(i++, "Zonda "),
                    ).sortedBy { brandModel -> brandModel.name.first() }
                )
                context.respond(brandsResponse)
            }
        )
    }

    override fun register(routing: Routing) {
        routing.statusRoute()
    }
}
