name: Pull Request CI

on:
  merge_group:
  pull_request:
    branches:
      - 'dev'

# Concurrency strategy:
#   github.workflow: distinguish this workflow from others
#   github.event_name: distinguish `push` event from `pull_request` and 'merge_group' event
#   github.ref_name: distinguish branch
#   github.repository: distinguish owner+repository
#
# Reference:
#   https://docs.github.com/en/actions/using-jobs/using-concurrency
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{github.ref_name}}-${{github.repository}}
  cancel-in-progress: true


jobs:
  validate_gradle_wrapper:
    name: "Validate gradle wrapper"
    uses: ./.github/workflows/call-validate-gradle-wrapper.yml
  info:
    name: "Display concurrency info"
    runs-on: ubuntu-latest
    needs: [ validate_gradle_wrapper ]
    steps:
      - run: |
          echo "github.workflow=${{ github.workflow }}"
          echo "github.event_name=${{ github.event_name }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.repository=${{ github.repository }}"
  check_kenerator_configuration:
    name: "Check config generation is fine"
    runs-on: ubuntu-latest
    needs: [ validate_gradle_wrapper ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run configuration kenerator
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: :modules:kenerator:configuration:run
  check_db_configuration:
    name: "Check sql generation is fine"
    runs-on: ubuntu-latest
    needs: [ validate_gradle_wrapper ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.17
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run SQL kenerator
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: :modules:kenerator:sql:run
      - name: Run test
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: :web-api:test